### ISSUE TITLE
Propose: Making xunit-file compatible with grunt-mocha-test

### ISSUE THREAD

**Issue by Stofkn** [peerigon/xunit-file#11]
Hi,

It should be nice if I can use this lib the same as some other reporters.
Just pass the path to the file as optional parameter, rather than environment variable.

 mochaTest: {
        'xunit-file-report': {
          options: {
              reporter: 'xunit-file',
              captureFile: 'test/xunit.xml'   
          },
          src: ['test/**/*-spec.js']
        },...

Thanks in advance!

Kind regards

Kristof

**Comment by matthaias** [comment]
Close?
