### ISSUE TITLE
DateTime formats.

### ISSUE THREAD

**Issue by whamBamDev** [peerigon/xunit-file#17]
Hi,

I've raised this issue to request that the format of the timestamp attribute (of the testsuite element) be changed from UTC format to XSD DateTime format (e.g. 2015-09-08T05:06:45).

This will keep the format in-line with the JUnit format and will allow better integration with tools that are likely to consume these reports (e.g. Jenkins).

More Info;
* http://help.catchsoftware.com/display/ET/JUnit+Format
* http://windyroad.com.au/dl/Open%20Source/JUnit.xsd

Cheers
Peter

**Comment by jhnns** [comment]
Sounds reasonable...

So afaict XSD is just `date.toISOString()`? According to [this documentation](http://www.w3schools.com/schema/schema_dtypes_date.asp) this should be true.

**Comment by whamBamDev** [comment]
I'd be happy with that, though in the schema definition there is a restriction to be down to the nearest second and not to include the fraction or seconds/timezone values. For my purposes it will be OK to have them and it strikes me as being logical to include those values so might as well go ahead.

I probably should raise another issue for this; I was going to suggest add a new feature to record the vital environment and process variables in the properties section of the XML (by default disabled, enable via an environment variable). I'm quite happen to have a go that this one, and to submit a patch with my suggestions.

**Comment by jhnns** [comment]
Yes, go head! :+1:

> though in the schema definition there is a restriction to be down to the nearest second and not to include the fraction or seconds/timezone values

It would be cool if you could implement this. You could call `date.toISOString()`, cut off the timezome, milliseconds, seconds and re-add the seconds depending on the milliseconds.

**Comment by whamBamDev** [comment]
No worries, I'll have a go, probably take a couple of weeks for me to get around to completing.

**Comment by whamBamDev** [comment]
Ok. I have some changes, I'm new to github so what is the best way to submit them?

**Comment by meaku** [comment]
Fork the repo and create a pull request. 

See 
- https://help.github.com/articles/fork-a-repo/
- https://help.github.com/articles/creating-a-pull-request/

**Comment by whamBamDev** [comment]
Many thanks for the doco links, they were very useful.

Pull request has now been created and ready for review.

**Comment by matthaias** [comment]
https://github.com/peerigon/xunit-file/pull/18

**Comment by whamBamDev** [comment]
Thanks for that, it's working well. I've raised issue https://github.com/mochajs/mocha/issues/1956 to get these changes included in the source xunit reporter.

**Comment by jhnns** [comment]
@whamBamDev :+1:
