### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by benurb** [peerigon/xunit-file#23]
Hey @matthaias ,

thanks for your great module 👍 
The only thing that bothers me a bit is that it still is in the 0.0.x version range, so the only way we can stay updated in a larger amount of projects is to use `0.0.x` in the package.json. That's a bit of a surprise bag then 😄  Maybe we get bugfixes, maybe we get major breaking changes. Did you consider using the semantic versioning specification for your releases?

Regards,
Ben

**Comment by matthaias** [comment]
Hey @benurb! Thanks for your feedback. To be honest, there is no reason this module is still 0.0.x. I'll change that.

**Comment by matthaias** [comment]
@benurb published as `v1.0.0`.
