### ISSUE TITLE
Support for outputs to multiple files?

### ISSUE THREAD

**Issue by matsev** [peerigon/xunit-file#26]
How can I configure xunit-file to write to different files for different tests?

Currently, I have a project setup in which I have one `test` folder for unit tests and one `itest` folder for integration tests. First, the unit tests are executed directly against the source code, if successful the application is packaged and deployed, and then integration tests are executed against the deployed app. I have two npm scripts in my `package.json` file:

```
"scripts": {
    "test": "mocha --recursive -R xunit-file",
    "itest": "mocha --recursive itest -R xunit-file"
}
```

The problem is when I execute `npm run itest` it will overwrite the result in `xunit.xml` generated by `npm test`. 

With the default xunit reporter it is possible to use `>` to redirect the output to different files like:

```
"scripts": {
    "test": "mocha --recursive -R xunit > xunit-test.xml",
    "itest": "mocha --recursive itest -R xunit > xunit-itest.xml"
}
```

The problem with this setup is that the default xunit reporter also include printouts from `console.log()`, which means that the resulting files not only contain valid xml but also log statements.

**Comment by leomelzer** [comment]
Hi @matsev! Thanks for reporting, sorry for the long delay. This is likely not relevant any longer but you can solve this using the environment variable to set the output file:

```
"scripts": {
    "test": "XUNIT_FILE=xunit-test.xml mocha --recursive -R xunit-file",
    "itest": "XUNIT_FILE=xunit-itest.xml mocha --recursive itest -R xunit-file"
}
```

For best cross platform support you'll likely want something like [cross-env](https://www.npmjs.com/package/cross-env).

Hope that helps! Thanks
