### ISSUE TITLE
path to config.js should not be module-relative

### ISSUE THREAD

**Issue by joma74** [peerigon/xunit-file#31]
Please give me an example where to put my config.js to. 

Looking at your source, the path seems to be module-realtive hard coded t.i. `../config.json`. So it only reads your distributed config.json, but never mine :confused:

**Comment by leomelzer** [comment]
Thanks for reporting, sorry for the long delay! True...this isn't solved the best way currently. We probably should have use something like https://github.com/davidtheclark/cosmiconfig to allow for easy configuration in a somewhat standardized way. 

Which option did you want to change? The filename can be changed by setting `process.env.XUNIT_FILE`. The other options are just controlling console output and we have sensible defaults.

I'll anyways go ahead and close this. Happy to look into better configuration solutions if there are use cases which aren't covered yet. Thanks!
