### ISSUE TITLE
npm vulnerability found on dateformat dependency

### ISSUE THREAD

**Issue by anderconal** [peerigon/xunit-file#34]
A **Regular Expression Denial of Service** vulnerability exists on **[dateformat](https://www.npmjs.com/package/dateformat)** dependency (see Dependencies section [here](https://www.npmjs.com/package/xunit-file))

The full path looks like this:

**_xunit-file > dateformat > meow > trim-newlines_**

**More information:**

https://www.npmjs.com/advisories/1753

**Remediation**

The remediation is to Upgrade the **trim-newlines library** to versions 3.0.1 or 4.0.1 or later. For this repository I'd say that the remediation would be to Upgrade the  **[dateformat](https://www.npmjs.com/package/dateformat)** library

**Comment by gagyibenedek** [comment]
I've created a PR that fixes the mentioned issue: https://github.com/peerigon/xunit-file/pull/35

**Comment by gagyibenedek** [comment]
Until this gets merged I've created a fork of xunit-file with fixed CVE-s: https://www.npmjs.com/package/xunit-file-secure
